-- CREATE TABLES
CREATE TABLE MANUFACTURERS (
    Manufacturer_ID INT AUTO_INCREMENT PRIMARY KEY,
    Manufacturer_Name VARCHAR(35) NOT NULL,
    Country VARCHAR(35) NOT NULL,
    YearFounded INT NOT NULL,
    Revenue_USD_Billion INTEGER NOT NULL
);


CREATE TABLE CARS (
    Model_ID INT AUTO_INCREMENT PRIMARY KEY,
    Manufacturer_ID INT,
    Model_Name VARCHAR(35) NOT NULL,
    Car_Type VARCHAR(35),
    Launch_Year INT NOT NULL,
    Car_Price DECIMAL(10,2),
    FOREIGN KEY(Manufacturer_ID) REFERENCES MANUFACTURERS(Manufacturer_ID)
);

CREATE TABLE REGIONS (
    Region_ID VARCHAR(2) PRIMARY KEY,
    Region_Name VARCHAR(55) NOT NULL
);


CREATE TABLE SALES (
    Sales_ID INT AUTO_INCREMENT,
    Model_ID INT,
    Region_ID VARCHAR(2),
    Sales_Year VARCHAR(4) NOT NULL,
    Units_Sold INT NOT NULL,
    PRIMARY KEY(Sales_ID),
    FOREIGN KEY (Model_ID) REFERENCES CARS (Model_ID),
    FOREIGN KEY (Region_ID) REFERENCES REGIONS(Region_ID)
);





